title: Jtown Dynasty
baseline: Your blogging assistant
description: THE fantasy football league of Jenkintown, powered by Cecil.
baseurl: /
canonicalurl: true
keywords: [Cecil, Static Site Generator, SSG]
author: Christian Geer
date:
  format: j F Y
  timezone: Europe/Paris
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: true # Content to the bottom of the sidebar
  theme: '' # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false # Reverse layout
