title: Jtown Dynasty
baseline: Jenkintown's Finest
description: THE fantasy football league of Jenkintown
baseurl: /
canonicalurl: true
keywords: [Cecil, Static Site Generator, SSG]
author: Christian Geer
date:
  format: F j, Y
  timezone: America/New_York
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: true # Content to the bottom of the sidebar
  theme: 'orange' # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false # Reverse layout
googleanalytics: "G-C4NCZ7X3VK"
